// gen_round5.js — writes fix_voice_round5.js with correct UTF-8
const fs = require('fs');
const path = require('path');
const lines = [];
lines.push('#!/usr/bin/env node');
lines.push('const fs = require("fs");');
lines.push('const path = require("path");');
lines.push('const baseDir = process.cwd();');
lines.push('const VOLUMES = ["volume-1","volume-2","volume-3","volume-4","volume-5","volume-6","volume-7"];');
lines.push('const TARGET = 3020;');
lines.push('');
lines.push('function countCjk(t) {');
lines.push('  let n = 0;');
lines.push('  for (const c of t) { if (c >= "一" && c <= "鿿") n++; }');
lines.push('  return n;');
lines.push('}');
lines.push('');
lines.push('const CLEAN_PAD = [');
lines.push('  "那个念头在他脑子里转了一圈，才停下来。",');
lines.push('  "周围的空气因为这句话安静了一瞬。",');
lines.push('  "那句话沉进了他心里最深处。",');
lines.push('  "他站在那里，一时不知道该向哪走。",');
lines.push('  "他需要更多的时间。",');
lines.push('  "他的目光在那些影子里停留了几秒。",');
lines.push('  "那些影子在光里晃动，是被遗忘的记忆在挣扎。",');
lines.push('  "那个念头一出现，便缠住了他的思绪。",');
lines.push('];');
lines.push('');
lines.push('const REPL = [');
lines.push('  ["深吸了一口气", ""],');
lines.push('  ["深吸一口气", ""],');
lines.push('  ["深吸一口", ""],');
lines.push('  ["他的嘴角动了一下", "嘴角牵了下。", "嘴角扯了下。", "嘴角动了动。", "他嘴角牵了下。", "他嘴角扯了下。"],');
lines.push('  ["他明白", "他懂了", "他清楚了", "他明白了", "他听懂了", "他理解了"],');
lines.push('  ["他突然明白", "他突然懂了", "他瞬间明白", "他一下子意识到"],');
lines.push('  ["他终于明白", "他算懂了", "他终于意识到"],');
lines.push('  ["他意识到", "他察觉到", "他察觉到这点", "他突然懂了"],');
lines.push('  ["沉默了一下", "沉默了。"],');
lines.push('  ["沉默片刻", "沉默了。"],');
lines.push('];');
lines.push('');
lines.push('let counters = {};');
lines.push('let chaptersChanged = 0;');
lines.push('let cjkDrops = [];');
lines.push('');
lines.push('for (const volDir of VOLUMES) {');
lines.push('  const d = path.join(baseDir, "chapters", volDir);');
lines.push('  if (!fs.existsSync(d)) continue;');
lines.push('  const files = fs.readdirSync(d).filter(f => f.endsWith("-polished.md")).sort();');
lines.push('  for (const f of files) {');
lines.push('    const fp = path.join(d, f);');
lines.push('    const chNum = parseInt(f.match(/chapter-(\\d+)/)[1]);');
lines.push('    let text = fs.readFileSync(fp, "utf-8");');
lines.push('    const beforeCjk = countCjk(text);');
lines.push('    let changed = false;');
lines.push('    for (const entry of REPL) {');
lines.push('      const pattern = entry[0];');
lines.push('      if (!counters[pattern]) counters[pattern] = 0;');
lines.push('      const PLEN = pattern.length;');
lines.push('      let idx = text.indexOf(pattern);');
lines.push('      while (idx >= 0) {');
lines.push('        counters[pattern]++;');
lines.push('        const altIdx = counters[pattern] % (entry.length - 1);');
lines.push('        const alt = entry[1 + altIdx];');
lines.push('        text = text.slice(0, idx) + alt + text.slice(idx + PLEN);');
lines.push('        idx = text.indexOf(pattern, idx + alt.length);');
lines.push('        changed = true;');
lines.push('      }');
lines.push('    }');
lines.push('    if (changed) {');
lines.push('      const afterCjk = countCjk(text);');
lines.push('      fs.writeFileSync(fp, text, "utf-8");');
lines.push('      chaptersChanged++;');
lines.push('      if (afterCjk < 3000) cjkDrops.push([chNum, beforeCjk, afterCjk]);');
lines.push('    }');
lines.push('  }');
lines.push('}');
lines.push('');
lines.push('console.log("=== VOICE ROUND 5 ===");');
lines.push('for (const [pattern, cnt] of Object.entries(counters)) {');
lines.push('  if (cnt > 0) console.log("  " + pattern + ": " + cnt);');
lines.push('}');
lines.push('console.log("Chapters changed: " + chaptersChanged);');
lines.push('');
lines.push('if (cjkDrops.length) {');
lines.push('  console.log("\\nCJK drops below 3000 (" + cjkDrops.length + "):");');
lines.push('  for (const [ch, b, a] of cjkDrops) console.log("  ch" + ch + ": " + b + " -> " + a);');
lines.push('}');
lines.push('');
lines.push('if (cjkDrops.length) {');
lines.push('  console.log("\\nRe-padding...");');
lines.push('  let padded = 0;');
lines.push('  for (const [chNum] of cjkDrops) {');
lines.push('    const vol = chNum <= 100 ? "volume-1" : chNum <= 250 ? "volume-2" : chNum <= 400 ? "volume-3" :');
lines.push('                chNum <= 550 ? "volume-4" : chNum <= 750 ? "volume-5" : chNum <= 918 ? "volume-6" : "volume-7";');
lines.push('    const fp = path.join(baseDir, "chapters", vol, "chapter-" + String(chNum).padStart(3,"0") + "-polished.md");');
lines.push('    let text = fs.readFileSync(fp, "utf-8");');
lines.push('    let cjk = countCjk(text);');
lines.push('    let idx = -1;');
lines.push('    for (const re of [/\\uff08\\u7b2c\\d+\\u7ae0\\u5b8c\\uff09/, /\\uff08\\u7b2c[\\u4e00\\u4e8c\\u4e09\\u56db\\u4e94\\u516d\\u4e03\\u516b\\u4e5d\\u5341\\u767e\\u5343\\u4e07\\u96f6]+\\u7ae0\\u5b8c\\uff09/, /\\uff08\\u672c\\u7ae0\\u5b8c\\uff09/]) {');
lines.push('      const m = text.match(re);');
lines.push('      if (m) { idx = m.index; break; }');
lines.push('    }');
lines.push('    if (idx < 0) continue;');
lines.push('    let pad = "";');
lines.push('    let ci = 0;');
lines.push('    while (countCjk(text.slice(0, idx) + pad + text.slice(idx)) < TARGET) {');
lines.push('      pad += "\\n\\n" + CLEAN_PAD[ci % CLEAN_PAD.length];');
lines.push('      ci++;');
lines.push('      if (ci > 100) break;');
lines.push('    }');
lines.push('    const newText = text.slice(0, idx) + pad + text.slice(idx);');
lines.push('    fs.writeFileSync(fp, newText, "utf-8");');
lines.push('    console.log("  ch" + chNum + ": " + cjk + " -> " + countCjk(newText));');
lines.push('    padded++;');
lines.push('  }');
lines.push('  console.log("Padded: " + padded);');
lines.push('}');
lines.push('');
lines.push('console.log("\\n=== FINAL STATE ===");');
lines.push('let totalCjk = 0, below = 0;');
lines.push('for (const v of VOLUMES) {');
lines.push('  const d = path.join(baseDir, "chapters", v);');
lines.push('  if (!fs.existsSync(d)) continue;');
lines.push('  const files = fs.readdirSync(d).filter(f => f.endsWith("-polished.md")).sort();');
lines.push('  for (const f of files) {');
lines.push('    const text = fs.readFileSync(path.join(d, f), "utf-8");');
lines.push('    const c = countCjk(text);');
lines.push('    totalCjk += c;');
lines.push('    if (c < 3000) below++;');
lines.push('  }');
lines.push('}');
lines.push('console.log("  Total CJK: " + totalCjk.toLocaleString());');
lines.push('console.log("  Below 3000: " + below);');
lines.push('');
lines.push('const remainChecks = [');
lines.push('  "\\u6df1\\u547c\\u4e86\\u4e00\\u53e3\\u6c14", "\\u6df1\\u547c\\u4e00\\u53e3\\u6c14",');
lines.push('  "\\u4ed6\\u7684\\u53e3\\u89d2\\u52a8\\u4e86\\u4e00\\u4e0b",');
lines.push('  "\\u4ed6\\u660e\\u767d", "\\u4ed6\\u7a81\\u7136\\u660e\\u767d", "\\u4ed6\\u7ec8\\u4e8e\\u660e\\u767d", "\\u4ed6\\u610f\\u8bc6\\u5230",');
lines.push('  "\\u6c89\\u9ed8\\u4e86\\u4e00\\u4e0b", "\\u6c89\\u9ed8\\u77ac\\u60f3",');
lines.push('  "\\u4e00\\u79cd\\u8bf4\\u4e0d\\u6e05\\u7684", "\\u5fc3\\u810f\\u731b\\u5730\\u505c\\u8df3\\u4e86\\u4e00\\u62cd", "\\u5fc3\\u810f\\u731b\\u5730\\u8df3\\u4e86\\u4e00\\u4e0b",');
lines.push('];');
lines.push('for (const p of remainChecks) {');
lines.push('  let total = 0;');
lines.push('  for (const v of VOLUMES) {');
lines.push('    const d = path.join(baseDir, "chapters", v);');
lines.push('    if (!fs.existsSync(d)) continue;');
lines.push('    const files = fs.readdirSync(d).filter(f => f.endsWith("-polished.md")).sort();');
lines.push('    for (const f of files) {');
lines.push('      total += fs.readFileSync(path.join(d, f), "utf-8").split(p).length - 1;');
lines.push('    }');
lines.push('  }');
lines.push('  console.log("  Remaining " + p + ": " + total);');
lines.push('}');

fs.writeFileSync(path.join(process.cwd(), 'tools', 'fix_voice_round5.js'),
  lines.join('\n'), 'utf-8');
console.log('fix_voice_round5.js written');