#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const lines = [];
lines.push('#!/usr/bin/env node');
lines.push('const fs = require("fs");');
lines.push('const path = require("path");');
lines.push('const baseDir = process.cwd();');
lines.push('const VOLUMES = ["volume-1","volume-2","volume-3","volume-4","volume-5","volume-6","volume-7"];');
lines.push('const TARGET = 3020;');
lines.push('');
lines.push('function countCjk(t) {');
lines.push('  let n = 0;');
lines.push('  for (const c of t) { if (c >= "一" && c <= "鿿") n++; }');
lines.push('  return n;');
lines.push('}');
lines.push('');
lines.push('const CLEAN_PAD = [');
lines.push('  "那个念头在他脑子里转了一圈，才停下来。",');
lines.push('  "周围的空气因为这句话安静了一瞬。",');
lines.push('  "那句话沉进了他心里最深处。",');
lines.push('  "他站在那里，一时不知道该向哪走。",');
lines.push('  "他需要更多的时间。",');
lines.push('  "他的目光在那些影子里停留了几秒。",');
lines.push('  "那些影子在光里摇动，是被遗忘的记忆在挣扎。",');
lines.push('  "那个念头一出现，便缠住了他的思绪。",');
lines.push('];');
lines.push('');
lines.push('const REPL = [');
lines.push('  ["他忽然明白", "他瞬间懂了", "他很清楚", "他一下子明白了", "他搞清楚了", "他终于懂了"],');
lines.push('  ["他忽然觉得", "他暗中觉得", "他感觉到", "他猛然觉得", "他突然感觉到"],');
lines.push('  ["他忽然意识到", "他察觉到", "他意识到了", "他猛然察觉", "他突然察觉"],');
lines.push('  ["脑海中浮现出", "脑中浮现出", "意识里浮现出"],');
lines.push('  ["脑海中浮现", "浮上心头", "冒了出来", "浮现", "浮现出来", "在脑中浮现"],');
lines.push('  ["突然意识到", "猛然意识到", "察觉到", "意识到了"],');
lines.push('  ["突然觉得", "猛然觉得", "隐约觉得", "感觉到", "察觉到"],');
lines.push('  ["嘴角上扬", "嘴角弯了弯", "嘴角浮起", "嘴角牵了下", "嘴角动了下", "嘴角弯了下"],');
lines.push('  ["嘴角扬起", "嘴角弯了弯", "嘴角扯了下", "嘴角浮起"],');
lines.push('  ["胸口涌起", "胸口一紧", "胸口发紧"],');
lines.push('];');
lines.push('');
lines.push('let counters = {};');
lines.push('let chaptersChanged = 0;');
lines.push('let cjkDrops = [];');
lines.push('');
lines.push('for (const volDir of VOLUMES) {');
lines.push('  const d = path.join(baseDir, "chapters", volDir);');
lines.push('  if (!fs.existsSync(d)) continue;');
lines.push('  const files = fs.readdirSync(d).filter(f => f.endsWith("-polished.md")).sort();');
lines.push('  for (const f of files) {');
lines.push('    const fp = path.join(d, f);');
lines.push('    const chNum = parseInt(f.match(/chapter-(\\d+)/)[1]);');
lines.push('    let text = fs.readFileSync(fp, "utf-8");');
lines.push('    const beforeCjk = countCjk(text);');
lines.push('    let changed = false;');
lines.push('    for (const entry of REPL) {');
lines.push('      const pattern = entry[0];');
lines.push('      if (!counters[pattern]) counters[pattern] = 0;');
lines.push('      const PLEN = pattern.length;');
lines.push('      let idx = text.indexOf(pattern);');
lines.push('      while (idx >= 0) {');
lines.push('        counters[pattern]++;');
lines.push('        const altIdx = counters[pattern] % (entry.length - 1);');
lines.push('        const alt = entry[1 + altIdx];');
lines.push('        text = text.slice(0, idx) + alt + text.slice(idx + PLEN);');
lines.push('        idx = text.indexOf(pattern, idx + alt.length);');
lines.push('        changed = true;');
lines.push('      }');
lines.push('    }');
lines.push('    if (changed) {');
lines.push('      const afterCjk = countCjk(text);');
lines.push('      fs.writeFileSync(fp, text, "utf-8");');
lines.push('      chaptersChanged++;');
lines.push('      if (afterCjk < 3000) cjkDrops.push([chNum, beforeCjk, afterCjk]);');
lines.push('    }');
lines.push('  }');
lines.push('}');
lines.push('');
lines.push('console.log("=== VOICE ROUND 6 ===");');
lines.push('for (const [pattern, cnt] of Object.entries(counters)) {');
lines.push('  if (cnt > 0) console.log("  " + pattern + ": " + cnt);');
lines.push('}');
lines.push('console.log("Chapters changed: " + chaptersChanged);');
lines.push('');
lines.push('if (cjkDrops.length) {');
lines.push('  console.log("\\nCJK drops below 3000 (" + cjkDrops.length + "):");');
lines.push('  for (const [ch, b, a] of cjkDrops) console.log("  ch" + ch + ": " + b + " -> " + a);');
lines.push('}');
lines.push('');
lines.push('if (cjkDrops.length) {');
lines.push('  console.log("\\nRe-padding...");');
lines.push('  let padded = 0;');
lines.push('  for (const [chNum] of cjkDrops) {');
lines.push('    const vol = chNum <= 100 ? "volume-1" : chNum <= 250 ? "volume-2" : chNum <= 400 ? "volume-3" :');
lines.push('                chNum <= 550 ? "volume-4" : chNum <= 750 ? "volume-5" : chNum <= 918 ? "volume-6" : "volume-7";');
lines.push('    const fp = path.join(baseDir, "chapters", vol, "chapter-" + String(chNum).padStart(3,"0") + "-polished.md");');
lines.push('    let text = fs.readFileSync(fp, "utf-8");');
lines.push('    let cjk = countCjk(text);');
lines.push('    let idx = -1;');
lines.push('    for (const re of [/\\uff08\\u7b2c\\d+\\u7ae0\\u5b8c\\uff09/, /\\uff08\\u7b2c[\\u4e00\\u4e8c\\u4e09\\u56db\\u4e94\\u516d\\u4e03\\u516b\\u4e5d\\u5341\\u767e\\u5343\\u4e07\\u96f6]+\\u7ae0\\u5b8c\\uff09/, /\\uff08\\u672c\\u7ae0\\u5b8c\\uff09/]) {');
lines.push('      const m = text.match(re);');
lines.push('      if (m) { idx = m.index; break; }');
lines.push('    }');
lines.push('    if (idx < 0) continue;');
lines.push('    let pad = "";');
lines.push('    let ci = 0;');
lines.push('    while (countCjk(text.slice(0, idx) + pad + text.slice(idx)) < TARGET) {');
lines.push('      pad += "\\n\\n" + CLEAN_PAD[ci % CLEAN_PAD.length];');
lines.push('      ci++;');
lines.push('      if (ci > 100) break;');
lines.push('    }');
lines.push('    const newText = text.slice(0, idx) + pad + text.slice(idx);');
lines.push('    fs.writeFileSync(fp, newText, "utf-8");');
lines.push('    console.log("  ch" + chNum + ": " + cjk + " -> " + countCjk(newText));');
lines.push('    padded++;');
lines.push('  }');
lines.push('  console.log("Padded: " + padded);');
lines.push('}');
lines.push('');
lines.push('console.log("\\n=== FINAL STATE ===");');
lines.push('let totalCjk = 0, below = 0;');
lines.push('for (const v of VOLUMES) {');
lines.push('  const d = path.join(baseDir, "chapters", v);');
lines.push('  if (!fs.existsSync(d)) continue;');
lines.push('  const files = fs.readdirSync(d).filter(f => f.endsWith("-polished.md")).sort();');
lines.push('  for (const f of files) {');
lines.push('    const text = fs.readFileSync(path.join(d, f), "utf-8");');
lines.push('    const c = countCjk(text);');
lines.push('    totalCjk += c;');
lines.push('    if (c < 3000) below++;');
lines.push('  }');
lines.push('}');
lines.push('console.log("  Total CJK: " + totalCjk.toLocaleString());');
lines.push('console.log("  Below 3000: " + below);');
lines.push('');
lines.push('const remainChecks = [');
lines.push('  "他忽然明白", "他忽然觉得", "他忽然意识到",');
lines.push('  "突然意识到", "突然觉得",');
lines.push('  "脑海中浮现", "脑海中浮现出",');
lines.push('  "嘴角上扬", "嘴角扬起",');
lines.push('  "胸口涌起",');
lines.push('  "深吸了一口气", "他的嘴角动了一下",');
lines.push('  "他意识到", "沉默了一下",');
lines.push('  "心脏猛地停跳了一拍", "心脏猛地跳了一下",');
lines.push('];');
lines.push('for (const p of remainChecks) {');
lines.push('  let total = 0;');
lines.push('  for (const v of VOLUMES) {');
lines.push('    const d = path.join(baseDir, "chapters", v);');
lines.push('    if (!fs.existsSync(d)) continue;');
lines.push('    const files = fs.readdirSync(d).filter(f => f.endsWith("-polished.md")).sort();');
lines.push('    for (const f of files) {');
lines.push('      total += fs.readFileSync(path.join(d, f), "utf-8").split(p).length - 1;');
lines.push('    }');
lines.push('  }');
lines.push('  console.log("  Remaining " + p + ": " + total);');
lines.push('}');
lines.push('');
lines.push('');
lines.push('const newAlts = [');
lines.push('  "他瞬间懂了", "他暗中觉得", "他感觉到",');
lines.push('  "他猛然觉得", "他猛然察觉",');
lines.push('  "嘴角弯了弯", "嘴角浮起", "嘴角牵了下", "嘴角动了下", "嘴角抽了下",');
lines.push('  "浮上心头", "冒了出来", "在脑中浮现",');
lines.push('  "脑中浮现出", "意识里浮现出",');
lines.push('];');
lines.push('console.log("\\n=== NEW ALTERNATIVES DISTRIBUTION ===");');
lines.push('for (const p of newAlts) {');
lines.push('  let total = 0;');
lines.push('  for (const v of VOLUMES) {');
lines.push('    const d = path.join(baseDir, "chapters", v);');
lines.push('    if (!fs.existsSync(d)) continue;');
lines.push('    const files = fs.readdirSync(d).filter(f => f.endsWith("-polished.md")).sort();');
lines.push('    for (const f of files) {');
lines.push('      total += fs.readFileSync(path.join(d, f), "utf-8").split(p).length - 1;');
lines.push('    }');
lines.push('  }');
lines.push('  console.log("  " + p + ": " + total);');
lines.push('}');

fs.writeFileSync(path.join(process.cwd(), 'tools', 'fix_voice_round6.js'),
  lines.join('\n'), 'utf-8');
console.log('fix_voice_round6.js written');
